namespace VIPCore;

public partial class VIPCore
{
    private const string DefaultGroupsJson = """
{
  "#Lite": {
    "AdminFlags": ["@css/reservation", "@css/vip"],
    "AntiFlash": { "self": false, "enemy": false, "teammates": true },
    "Armor": { "value": 100, "helmet": false },
    "Bhop": { "autostrafe": false, "max_speed": 350, "jump_boost": 1.05, "jump_velocity": 300 },
    "Tag": { "tag": "{BlueGrey}[LITE]", "name_color": "bluegrey", "chat_color": "default", "tab": "[LITE]" },
    "ColoredModel": ["Rainbow rainbow", "Mavi #0000FF", "Yesil #00FF00"],
    "DamageResist": { "percent": 15, "only_with_weapon": "", "ignore_teammates": true, "ignore_self": true },
    "DecoyTeleport": { "limit": 3 },
    "DefuseKit": true,
    "ExtraHP": 110,
    "ExtraJump": { "count": 1, "limit": 3 },
    "ExtraMoney": { "amount": 500 },
    "ExtraSpeed": { "multiplier": 1.1, "only_with_weapon": "weapon_knife" },
    "FallDamage": { "percent": 50, "count": 0 },
    "Fov": [50, 60],
    "HealthRegen": { "hp_per_tick": 3, "interval": 1.0, "delay_after_dmg": 5 },
    "Healthshot": 1,
    "JoinMessage": { "join_message": "", "leave_message": "" },
    "PlayerGlow": { "range": 300, "team": -1, "colors": ["Rainbow rainbow", "Mavi #0000FF", "Yesil #00FF00"] },
    "PlayerTrail": { "width": 1.0, "lifetime": 2.0, "colors": ["Rainbow rainbow", "Mavi #0000FF", "Yesil #00FF00"] },
    "SmokeColor": ["Beyaz #FFFFFF", "Kirmizi #FF0000"],
    "SpawnProtection": 2,
    "VIPChat": true,
    "GiveZeus": true
  },
  "#Plus": {
    "AdminFlags": ["@css/reservation", "@css/vip"],
    "AntiFlash": { "self": true, "enemy": true, "teammates": true },
    "AntiHS": { "percent": 0, "only_with_weapon": "" },
    "Armor": { "value": 100, "helmet": true },
    "ArmorRegen": { "armor_per_tick": 10, "interval": 1.0, "delay_after_dmg": 2, "max_armor": 100, "give_helmet_when_full": true },
    "AutoHS": { "multiplier": 4, "only_with_weapon": "", "ignore_teammates": true },
    "Bhop": { "autostrafe": true, "max_speed": 500, "jump_boost": 1.1, "jump_velocity": 300 },
    "BulletTrail": { "width": 1.5, "lifetime": 0.6, "only_with_weapon": "", "colors": ["Rainbow rainbow", "Kirmizi #FF0000", "Mavi #0000FF", "Yesil #00FF00"] },
    "BuyTeamWeapon": { "galil": true, "ak47": true, "sg553": true, "glock": true, "mac10": true, "tec9": true, "sawedoff": true, "g3sg1": true, "p2000": true, "mag7": true, "fiveseven": true, "famas": true, "m4a1": true, "m4a4": true, "aug": true, "scar20": true, "mp9": true, "usp": true },
    "Tag": { "tag": "{Gold}[PLUS]", "name_color": "gold", "chat_color": "default", "tab": "[PLUS]" },
    "ColoredModel": ["Rainbow rainbow", "Kirmizi #FF0000", "Yesil #00FF00", "Mavi #0000FF", "Sari #FFFF00", "Mor #A020F0"],
    "DamageDealt": { "percent": 50, "only_with_weapon": "", "ignore_teammates": true, "ignore_self": true },
    "DamageResist": { "percent": 40, "only_with_weapon": "", "ignore_teammates": true, "ignore_self": true },
    "DecoyTeleport": { "limit": 0 },
    "DefuseKit": true,
    "ExtraHP": 150,
    "ExtraJump": { "count": 2, "limit": 0 },
    "ExtraMoney": { "amount": 4000 },
    "ExtraSpeed": { "multiplier": 1.3, "only_with_weapon": "" },
    "FallDamage": { "percent": 0, "count": 0 },
    "FastDefuse": { "time": 1, "immune_while_burning": true },
    "FastPlant": { "time": 1, "immune_while_burning": true },
    "Fov": [50, 60, 70, 80, 90, 100, 110, 120],
    "GiveWeapon": ["weapon_ak47", "weapon_m4a1", "weapon_awp", "weapon_deagle"],
    "Glaz": true,
    "Gravity": [1.0, 0.8, 0.5, 0.3],
    "GrenadeTrail": { "width": 1.5, "lifetime": 2.5, "colors": ["Rainbow rainbow", "Kirmizi #FF0000", "Mavi #0000FF", "Yesil #00FF00"] },
    "HealthRegen": { "hp_per_tick": 10, "interval": 1.0, "delay_after_dmg": 2 },
    "Healthshot": 2,
    "InfiniteAmmo": { "only_weapon": "" },
    "JoinMessage": { "join_message": "{Gold}{name}{Default} sunucuya katildi {Green}(PLUS VIP)", "leave_message": "{Gold}{name}{Default} sunucudan ayrildi" },
    "KillScreen": { "duration": 1.0 },
    "OneShot": { "weapons": "weapon_awp,weapon_ssg08" },
    "PlayerGlow": { "range": 300, "team": -1, "colors": ["Rainbow rainbow", "Kirmizi #FF0000", "Mavi #0000FF", "Yesil #00FF00", "Sari #FFFF00", "Mor #A020F0"] },
    "PlayerTrail": { "width": 1.5, "lifetime": 2.5, "colors": ["Rainbow rainbow", "Kirmizi #FF0000", "Mavi #0000FF", "Yesil #00FF00", "Sari #FFFF00", "Mor #A020F0"] },
    "ReflectDamage": { "reflect_percent": 50, "max_per_shot": 100, "only_with_weapon": "", "ignore_teammates": true, "ignore_self": true },
    "SmokeColor": ["Beyaz #FFFFFF", "Kirmizi #FF0000", "Yesil #00FF00", "Mavi #0000FF", "Sari #FFFF00", "Mor #A020F0"],
    "SpawnProtection": 4,
    "Thirdperson": { "distance": 120 },
    "Vampire": { "heal_percent": 75, "only_with_weapon": "", "max_overheal": 120, "ignore_teammates": true },
    "VIPChat": true,
    "GiveZeus": true,
    "WeaponAmmo": [
      { "weapon_name": "weapon_ak47", "ammo": 30, "reserve": 3 },
      { "weapon_name": "weapon_deagle", "ammo": 7, "reserve": 3 }
    ],
    "FastReload": { "only_with_weapon": "" },
    "GrenadeKit": { "flash": 2, "smoke": 1, "he": 3, "molotov": 1, "decoy": 0 },
    "TeamHeal": { "minhp": 5, "percent": 50, "only_with_weapon": "" },
    "SmokeEffect": {
      "poison": { "minhp": 10, "damage": 2, "tick": 0.5, "radius": 180, "smokecolor": [255, 0, 255], "ignore_teammates": true, "ignore_self": true, "limit": 0 },
      "heal": { "heal": 2, "tick": 0.5, "radius": 180, "smokecolor": [0, 255, 0], "ignore_teammates": false, "ignore_self": false, "ignore_enemy": true, "limit": 0 },
      "slow": { "percent": 30, "minspeed": 100, "radius": 180, "smokecolor": [0, 0, 255], "ignore_teammates": true, "ignore_self": true, "ignore_enemy": false, "limit": 0 }
    },
    "RadarHack": { "duration_on": 1, "duration_off": 0 },
    "Invisibility": { "only_stopped": true, "dmg_after_invis": 2.0, "only_with_weapon": "" },
    "PoisonBullet": { "minhp": 10, "damage": 2, "damagetick": 1.0, "only_with_weapon": "", "ignore_teammates": true },
    "GlueGrenade": { "only_grenades": "flashbang,hegrenade" },
    "Spy": true,
    "GrenadeResist": { "percent": 50, "only_with_grenade": "he,molotov,inferno", "ignore_teammates": true, "ignore_self": true },
    "Silent": { "only_with_weapon": "" },
    "ZeusCooldown": { "cooldown": 5, "limit": 0 }
  }
}
""";
}
