namespace VIPCore;

public partial class VIPCore
{
    private const string DefaultGroupsJson = """
{
  "#Lite": {
    "AdminFlags": ["@css/reservation", "@css/vip"],
    "AntiFlash": { "self": false, "enemy": false, "teammates": true },
    "Armor": { "value": 100, "helmet": false },
    "Bhop": { "autostrafe": false, "max_speed": 350, "jump_boost": 1.05, "jump_velocity": 300 },
    "ChatTag": { "tag": "{BlueGrey}[LITE]", "name_color": "bluegrey", "chat_color": "default" },
    "ColoredModel": ["Rainbow rainbow", "Mavi #0000FF", "Yesil #00FF00"],
    "DamageResist": { "percent": 15, "only_with_weapon": "" },
    "DecoyTeleport": { "limit": 3 },
    "DefuseKit": true,
    "ExtraHP": 110,
    "ExtraJump": { "count": 1, "limit": 3 },
    "ExtraMoney": { "amount": 500 },
    "ExtraSpeed": { "multiplier": 1.1, "only_with_weapon": "weapon_knife" },
    "FallDamage": { "percent": 50, "count": 0 },
    "Fov": [50, 60],
    "HealthRegen": { "hp_per_tick": 3, "interval": 1.0, "delay_after_dmg": 5, "max_hp": 100 },
    "Healthshot": 1,
    "JoinMessage": { "join_message": "", "leave_message": "" },
    "PlayerGlow": { "range": 300, "team": -1, "colors": ["Rainbow rainbow", "Mavi #0000FF", "Yesil #00FF00"] },
    "PlayerTrail": { "width": 1.0, "lifetime": 2.0, "colors": ["Rainbow rainbow", "Mavi #0000FF", "Yesil #00FF00"] },
    "SmokeColor": ["Beyaz #FFFFFF", "Kirmizi #FF0000"],
    "SpawnProtection": 2,
    "VIPChat": true,
    "Zeus": true
  },
  "#Plus": {
    "AdminFlags": ["@css/reservation", "@css/vip"],
    "AntiFlash": { "self": true, "enemy": true, "teammates": true },
    "AntiHS": { "percent": 0, "only_with_weapon": "" },
    "Armor": { "value": 100, "helmet": true },
    "ArmorRegen": { "armor_per_tick": 10, "interval": 1.0, "delay_after_dmg": 2, "max_armor": 100, "give_helmet_when_full": true },
    "AutoHS": { "multiplier": 4, "only_with_weapon": "" },
    "Bhop": { "autostrafe": true, "max_speed": 500, "jump_boost": 1.1, "jump_velocity": 300 },
    "BulletTrail": { "width": 1.5, "lifetime": 0.6, "only_with_weapon": "", "colors": ["Rainbow rainbow", "Kirmizi #FF0000", "Mavi #0000FF", "Yesil #00FF00"] },
    "BuyTeamWeapon": { "galil": true, "ak47": true, "sg553": true, "glock": true, "mac10": true, "tec9": true, "sawedoff": true, "g3sg1": true, "p2000": true, "mag7": true, "fiveseven": true, "famas": true, "m4a1": true, "m4a4": true, "aug": true, "scar20": true, "mp9": true, "usp": true },
    "ChatTag": { "tag": "{Gold}[PLUS]", "name_color": "gold", "chat_color": "default" },
    "ColoredModel": ["Rainbow rainbow", "Kirmizi #FF0000", "Yesil #00FF00", "Mavi #0000FF", "Sari #FFFF00", "Mor #A020F0"],
    "DamageDealt": { "percent": 50, "only_with_weapon": "" },
    "DamageResist": { "percent": 40, "only_with_weapon": "" },
    "DecoyTeleport": { "limit": 0 },
    "DefuseKit": true,
    "ExtraHP": 150,
    "ExtraJump": { "count": 2, "limit": 0 },
    "ExtraMoney": { "amount": 4000 },
    "ExtraSpeed": { "multiplier": 1.3, "only_with_weapon": "" },
    "FallDamage": { "percent": 0, "count": 0 },
    "FastDefuse": { "time": 1, "immune_while_burning": true },
    "FastPlant": { "time": 1, "immune_while_burning": true },
    "Fov": [50, 60, 70, 80, 90, 100, 110, 120],
    "GiveWeapon": ["weapon_ak47", "weapon_m4a1", "weapon_awp", "weapon_deagle"],
    "Glaz": true,
    "Gravity": [1.0, 0.8, 0.5, 0.3],
    "GrenadeTrail": { "width": 1.5, "lifetime": 2.5, "colors": ["Rainbow rainbow", "Kirmizi #FF0000", "Mavi #0000FF", "Yesil #00FF00"] },
    "HealthRegen": { "hp_per_tick": 10, "interval": 1.0, "delay_after_dmg": 2, "max_hp": 150 },
    "Healthshot": 2,
    "InfiniteAmmo": { "only_weapon": "" },
    "JoinMessage": { "join_message": "{Gold}{name}{Default} sunucuya katildi {Green}(PLUS VIP)", "leave_message": "{Gold}{name}{Default} sunucudan ayrildi" },
    "KillScreen": { "duration": 1.0 },
    "OneShot": { "weapons": "weapon_awp,weapon_ssg08" },
    "PlayerGlow": { "range": 300, "team": -1, "colors": ["Rainbow rainbow", "Kirmizi #FF0000", "Mavi #0000FF", "Yesil #00FF00", "Sari #FFFF00", "Mor #A020F0"] },
    "PlayerTrail": { "width": 1.5, "lifetime": 2.5, "colors": ["Rainbow rainbow", "Kirmizi #FF0000", "Mavi #0000FF", "Yesil #00FF00", "Sari #FFFF00", "Mor #A020F0"] },
    "ReflectDamage": { "reflect_percent": 50, "max_per_shot": 100, "only_with_weapon": "" },
    "SmokeColor": ["Beyaz #FFFFFF", "Kirmizi #FF0000", "Yesil #00FF00", "Mavi #0000FF", "Sari #FFFF00", "Mor #A020F0"],
    "SpawnProtection": 4,
    "Thirdperson": { "distance": 120 },
    "Vampire": { "heal_percent": 75, "only_with_weapon": "", "max_overheal": 120 },
    "VIPChat": true,
    "Zeus": true
  }
}
""";
}
